// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahafProjesi.Data;

#nullable disable

namespace SahafProjesi.Migrations
{
    [DbContext(typeof(SahafDbContext))]
    partial class SahafDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SahafProjesi.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAdi = "Roman"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAdi = "Makale"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAdi = "Hikaye"
                        },
                        new
                        {
                            KategoriID = 4,
                            KategoriAdi = "Felsefe"
                        });
                });

            modelBuilder.Entity("SahafProjesi.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapID"));

                    b.Property<DateTime>("BasimYili")
                        .HasColumnType("datetime2");

                    b.Property<int>("BaskiSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("money");

                    b.Property<string>("KapakResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitapOzeti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("YayineviID")
                        .HasColumnType("int");

                    b.Property<int?>("YazarID")
                        .HasColumnType("int");

                    b.HasKey("KitapID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("YayineviID");

                    b.HasIndex("YazarID");

                    b.ToTable("Kitaplar");

                    b.HasData(
                        new
                        {
                            KitapID = 1,
                            BasimYili = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 5000,
                            Fiyat = 50m,
                            KapakResmi = "simyaci.jpg",
                            KategoriID = 2,
                            KitapAdi = "Simyacı",
                            KitapOzeti = "Simyacı, Paulo Coelho'nun, kişisel efsaneyi takip ederek mutluluğu ve anlamı bulma yolculuğunu anlatan bir roman.",
                            KullaniciID = 1,
                            YayineviID = 1,
                            YazarID = 1
                        },
                        new
                        {
                            KitapID = 2,
                            BasimYili = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 7500,
                            Fiyat = 60m,
                            KapakResmi = "1984.jpg",
                            KategoriID = 3,
                            KitapAdi = "1984",
                            KitapOzeti = "George Orwell'in distopik bir geleceği anlattığı çarpıcı roman.",
                            KullaniciID = 2,
                            YayineviID = 2,
                            YazarID = 2
                        },
                        new
                        {
                            KitapID = 3,
                            BasimYili = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 10000,
                            Fiyat = 45m,
                            KapakResmi = "kucukprens.jpg",
                            KategoriID = 1,
                            KitapAdi = "Küçük Prens",
                            KitapOzeti = "Antoine de Saint-Exupéry'nin çocuklar ve yetişkinler için felsefi     bir             başyapıtı.",
                            KullaniciID = 2,
                            YayineviID = 3,
                            YazarID = 3
                        },
                        new
                        {
                            KitapID = 4,
                            BasimYili = new DateTime(2019, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 6500,
                            Fiyat = 70m,
                            KapakResmi = "sefiller.jpg",
                            KategoriID = 3,
                            KitapAdi = "Sefiller",
                            KitapOzeti = "Victor Hugo'nun adalet, aşk ve fedakarlık üzerine unutulmaz   eseri.",
                            KullaniciID = 1,
                            YayineviID = 4,
                            YazarID = 4
                        },
                        new
                        {
                            KitapID = 5,
                            BasimYili = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 9000,
                            Fiyat = 80m,
                            KapakResmi = "sucveceza.jpg",
                            KategoriID = 3,
                            KitapAdi = "Suç ve Ceza",
                            KitapOzeti = "Fyodor Dostoyevski'nin, ahlak ve vicdan üzerine derin bir         incelemesi.",
                            KullaniciID = 2,
                            YayineviID = 3,
                            YazarID = 2
                        },
                        new
                        {
                            KitapID = 6,
                            BasimYili = new DateTime(2022, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 15000,
                            Fiyat = 85m,
                            KapakResmi = "harrypotter1.jpg",
                            KategoriID = 4,
                            KitapAdi = "Harry Potter ve Felsefe Taşı",
                            KitapOzeti = "J.K. Rowling'in büyücülük dünyasına giriş yaptığı ilk kitap.",
                            KullaniciID = 1,
                            YayineviID = 1,
                            YazarID = 2
                        },
                        new
                        {
                            KitapID = 7,
                            BasimYili = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 8000,
                            Fiyat = 50m,
                            KapakResmi = "ucurtmaavcisi.jpg",
                            KategoriID = 2,
                            KitapAdi = "Uçurtma Avcısı",
                            KitapOzeti = "Khaled Hosseini'nin dostluk ve ihanet temalarını işlediği     unutulmaz       roman.",
                            KullaniciID = 1,
                            YayineviID = 4,
                            YazarID = 3
                        },
                        new
                        {
                            KitapID = 8,
                            BasimYili = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 5000,
                            Fiyat = 55m,
                            KapakResmi = "beyazzambaklar.jpg",
                            KategoriID = 2,
                            KitapAdi = "Beyaz Zambaklar Ülkesinde",
                            KitapOzeti = "Grigory Petrov'un toplumsal gelişimi anlatan klasik eseri.",
                            KullaniciID = 2,
                            YayineviID = 1,
                            YazarID = 1
                        },
                        new
                        {
                            KitapID = 9,
                            BasimYili = new DateTime(2021, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 12000,
                            Fiyat = 40m,
                            KapakResmi = "sekerportakali.jpg",
                            KategoriID = 1,
                            KitapAdi = "Şeker Portakalı",
                            KitapOzeti = "José Mauro de Vasconcelos'un çocukluk üzerine etkileyici  hikayesi.",
                            KullaniciID = 1,
                            YayineviID = 3,
                            YazarID = 2
                        },
                        new
                        {
                            KitapID = 10,
                            BasimYili = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BaskiSayisi = 8500,
                            Fiyat = 45m,
                            KapakResmi = "hayvanciftligi.jpg",
                            KategoriID = 3,
                            KitapAdi = "Hayvan Çiftliği",
                            KitapOzeti = "George Orwell'in, toplumsal eleştirilerle dolu hiciv eseri.",
                            KullaniciID = 2,
                            YayineviID = 2,
                            YazarID = 2
                        });
                });

            modelBuilder.Entity("SahafProjesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Yas")
                        .HasColumnType("int");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciID = 1,
                            Ad = "Rabia",
                            KullaniciAdi = "Rabia",
                            Sifre = "a730b6202d87981256d6b065cccf2786",
                            Yas = 26
                        },
                        new
                        {
                            KullaniciID = 2,
                            Ad = "Ayşe",
                            KullaniciAdi = "Ayse",
                            Sifre = "bb05576d9620bd292530d51112052df2",
                            Yas = 30
                        });
                });

            modelBuilder.Entity("SahafProjesi.Models.Yayinevi", b =>
                {
                    b.Property<int>("YayineviID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YayineviID"));

                    b.Property<string>("YayineviAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YayineviID");

                    b.ToTable("Yayinevleri");

                    b.HasData(
                        new
                        {
                            YayineviID = 1,
                            YayineviAdi = "Can"
                        },
                        new
                        {
                            YayineviID = 2,
                            YayineviAdi = "İş Bankası"
                        },
                        new
                        {
                            YayineviID = 3,
                            YayineviAdi = "Yapı Kredi Yayınları"
                        },
                        new
                        {
                            YayineviID = 4,
                            YayineviAdi = "İthaki"
                        });
                });

            modelBuilder.Entity("SahafProjesi.Models.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarID"));

                    b.Property<string>("YazarAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YazarSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazarID");

                    b.ToTable("Yazarlar");

                    b.HasData(
                        new
                        {
                            YazarID = 1,
                            YazarAdi = "Paulo",
                            YazarSoyadi = "Coelho"
                        },
                        new
                        {
                            YazarID = 2,
                            YazarAdi = "Irvın",
                            YazarSoyadi = "Yalom"
                        },
                        new
                        {
                            YazarID = 3,
                            YazarAdi = "Jose",
                            YazarSoyadi = "Saramago"
                        },
                        new
                        {
                            YazarID = 4,
                            YazarAdi = "Stefan",
                            YazarSoyadi = "Zweig"
                        });
                });

            modelBuilder.Entity("SahafProjesi.Models.Kitap", b =>
                {
                    b.HasOne("SahafProjesi.Models.Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriID");

                    b.HasOne("SahafProjesi.Models.Kullanici", "Kullanici")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KullaniciID");

                    b.HasOne("SahafProjesi.Models.Yayinevi", "Yayinevi")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YayineviID");

                    b.HasOne("SahafProjesi.Models.Yazar", "Yazar")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YazarID");

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");

                    b.Navigation("Yayinevi");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("SahafProjesi.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("SahafProjesi.Models.Kullanici", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("SahafProjesi.Models.Yayinevi", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("SahafProjesi.Models.Yazar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
